latest

diff --git a/php-worker/Dockerfile b/php-worker/Dockerfile
--- a/php-worker/Dockerfile
+++ b/php-worker/Dockerfile
@@ -4,10 +4,20 @@
 #--------------------------------------------------------------------------
 #
 
-ARG PHP_VERSION=${PHP_VERSION}
-FROM php:${PHP_VERSION}-alpine
+ARG LARADOCK_PHP_VERSION
+FROM php:${LARADOCK_PHP_VERSION}-alpine
 
 LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"
+
+ARG LARADOCK_PHP_VERSION
+
+# If you're in China, or you need to change sources, will be set CHANGE_SOURCE to true in .env.
+
+ARG CHANGE_SOURCE=false
+RUN if [ ${CHANGE_SOURCE} = true ]; then \
+    # Change application source from dl-cdn.alpinelinux.org to aliyun source
+    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
+;fi
 
 RUN apk --update add wget \
   curl \
@@ -21,6 +31,7 @@ RUN apk --update add wget \
   autoconf \
   cyrus-sasl-dev \
   libgsasl-dev \
+  oniguruma-dev \
   supervisor
 
 RUN docker-php-ext-install mysqli mbstring pdo pdo_mysql tokenizer xml pcntl
@@ -34,6 +45,27 @@ ENV PGID ${PGID}
 
 RUN addgroup -g ${PGID} laradock && \
   adduser -D -G laradock -u ${PUID} laradock
+
+#Install BZ2:
+ARG INSTALL_BZ2=false
+RUN if [ ${INSTALL_BZ2} = true ]; then \
+  apk --update add bzip2-dev; \
+  docker-php-ext-install bz2; \
+fi
+
+#Install GD package:
+ARG INSTALL_GD=false
+RUN if [ ${INSTALL_GD} = true ]; then \
+   apk add --update --no-cache libpng-dev; \
+   docker-php-ext-install gd \
+;fi
+
+#Install GMP package:
+ARG INSTALL_GMP=false
+RUN if [ ${INSTALL_GMP} = true ]; then \
+   apk add --update --no-cache gmp gmp-dev \
+   && docker-php-ext-install gmp \
+;fi
 
 #Install SOAP package:
 ARG INSTALL_SOAP=false
@@ -56,18 +88,23 @@ RUN if [ ${INSTALL_PGSQL} = true ]; then \
 
 # Install ZipArchive:
 ARG INSTALL_ZIP_ARCHIVE=false
-RUN if [ ${INSTALL_ZIP_ARCHIVE} = true ]; then \
-  apk --update add libzip-dev && \
-  docker-php-ext-configure zip --with-libzip && \
-  # Install the zip extension
-  docker-php-ext-install zip \
-  ;fi
+RUN set -eux; \
+  if [ ${INSTALL_ZIP_ARCHIVE} = true ]; then \
+    apk --update add libzip-dev && \
+    if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ]; then \
+      docker-php-ext-configure zip; \
+    else \
+      docker-php-ext-configure zip --with-libzip; \
+    fi && \
+    # Install the zip extension
+    docker-php-ext-install zip \
+;fi
 
 # Install MySQL Client:
 ARG INSTALL_MYSQL_CLIENT=false
 RUN if [ ${INSTALL_MYSQL_CLIENT} = true ]; then \
-  apk --update add mysql-client \
-  ;fi
+      apk --update add mysql-client \
+;fi
 
 # Install FFMPEG:
 ARG INSTALL_FFMPEG=false
@@ -84,6 +121,17 @@ RUN if [ ${INSTALL_AMQP} = true ]; then \
   docker-php-ext-enable amqp && \
   docker-php-ext-install sockets \
   ;fi
+
+# Install Gearman:
+ARG INSTALL_GEARMAN=false
+
+RUN if [ ${INSTALL_GEARMAN} = true ]; then \
+    sed -i "\$ahttp://dl-cdn.alpinelinux.org/alpine/edge/main" /etc/apk/repositories && \
+    sed -i "\$ahttp://dl-cdn.alpinelinux.org/alpine/edge/community" /etc/apk/repositories && \
+    sed -i "\$ahttp://dl-cdn.alpinelinux.org/alpine/edge/testing" /etc/apk/repositories && \
+    apk --update add php7-gearman && \
+    sh -c 'echo "extension=/usr/lib/php7/modules/gearman.so" > /usr/local/etc/php/conf.d/gearman.ini' \
+;fi
 
 # Install Cassandra drivers:
 ARG INSTALL_CASSANDRA=false
@@ -103,7 +151,7 @@ RUN if [ ${INSTALL_CASSANDRA} = true ]; then \
   && make >/dev/null 2>&1 \
   && make install \
   && docker-php-ext-enable cassandra \
-  ;fi
+;fi
 
 # Install Phalcon ext
 ARG INSTALL_PHALCON=false
@@ -111,28 +159,27 @@ ARG PHALCON_VERSION
 ENV PHALCON_VERSION ${PHALCON_VERSION}
 
 RUN if [ $INSTALL_PHALCON = true ]; then \
-  apk --update add unzip gcc make re2c bash\
-  && curl -L -o /tmp/cphalcon.zip https://github.com/phalcon/cphalcon/archive/v${PHALCON_VERSION}.zip \
-  && unzip -d /tmp/ /tmp/cphalcon.zip \
-  && cd /tmp/cphalcon-${PHALCON_VERSION}/build \
-  && ./install \
-  && rm -rf /tmp/cphalcon* \
-  ;fi
+    apk --update add unzip gcc make re2c bash\
+    && curl -L -o /tmp/cphalcon.zip https://github.com/phalcon/cphalcon/archive/v${PHALCON_VERSION}.zip \
+    && unzip -d /tmp/ /tmp/cphalcon.zip \
+    && cd /tmp/cphalcon-${PHALCON_VERSION}/build \
+    && ./install \
+    && rm -rf /tmp/cphalcon* \
+;fi
 
+ARG INSTALL_GHOSTSCRIPT=false
 RUN if [ $INSTALL_GHOSTSCRIPT = true ]; then \
-  apk --update add ghostscript \
-  ;fi
+    apk --update add ghostscript \
+;fi
 
-#Install GMP package:
-ARG INSTALL_GMP=false
-RUN if [ ${INSTALL_GMP} = true ]; then \
-  apk add --update --no-cache gmp gmp-dev \
-  && docker-php-ext-install gmp \
-  ;fi
-
-RUN rm /var/cache/apk/* \
-  && mkdir -p /var/www
-
+# Install Redis package:
+ARG INSTALL_REDIS=false
+RUN if [ ${INSTALL_REDIS} = true ]; then \
+    # Install Redis Extension
+    printf "\n" | pecl install -o -f redis \
+    &&  rm -rf /tmp/pear \
+    &&  docker-php-ext-enable redis \
+;fi
 
 ###########################################################################
 # Swoole EXTENSION
@@ -141,18 +188,18 @@ RUN rm /var/cache/apk/* \
 ARG INSTALL_SWOOLE=false
 
 RUN if [ ${INSTALL_SWOOLE} = true ]; then \
-  # Install Php Swoole Extension
-  if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
-  pecl -q install swoole-2.0.10; \
-  else \
-  if [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then \
-  pecl install swoole-2.2.0; \
-  else \
-  pecl install swoole; \
-  fi \
-  fi \
-  && docker-php-ext-enable swoole \
-  ;fi
+    # Install Php Swoole Extension
+    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
+      pecl -q install swoole-2.0.10; \
+    else \
+      if [ $(php -r "echo PHP_MINOR_VERSION;") = "0" ]; then \
+        pecl install swoole-2.2.0; \
+      else \
+        pecl install swoole; \
+      fi \
+    fi \
+    && docker-php-ext-enable swoole \
+;fi
 
 ###########################################################################
 # Taint EXTENSION
@@ -192,7 +239,7 @@ ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
 #
 # If you need to modify this image, feel free to do it right here.
 #
-# -- Your awesome modifications go here -- #
+    # -- Your awesome modifications go here -- #
 
 #
 #--------------------------------------------------------------------------
@@ -207,5 +254,9 @@ RUN php -v | head -n 1 | grep -q "PHP ${PHP_VERSION}."
 # Final Touch
 #--------------------------------------------------------------------------
 #
+
+# Clean up
+RUN rm /var/cache/apk/* \
+    && mkdir -p /var/www
 
 WORKDIR /etc/supervisor/conf.d/
